name: kazan_guide
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.3

environment:
  sdk: ^3.7.2

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_flavor: ^3.1.4
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  logger: ^2.6.1
  open_route_service: ^1.2.7
  flutter_map_location_marker: ^10.1.0
  geolocator: ^14.0.2
  audioplayers: ^6.5.0
  num_remap: ^1.0.2
  go_router: ^17.0.0
  photo_view: ^0.15.0
  firebase_core: ^4.2.1
  firebase_analytics: ^12.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/route_1/
    - assets/images/route_1/main/
    - assets/images/route_1/points/
    - assets/images/route_1/points_full/
    - assets/images/route_2/
    - assets/images/route_2/main/
    - assets/images/route_2/points/
    - assets/images/route_2/points_full/
    - assets/audio/route_1/ru/
    - assets/audio/route_1/tat/
    - assets/audio/route_2/ru/
    - assets/audio/route_2/tat/
    - assets/data/routes.json
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700