name: kazan_guide
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_flavor: ^3.1.4
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  logger: ^2.6.1
  open_route_service: ^1.2.7
  flutter_map_location_marker: ^10.1.0
  geolocator: ^14.0.2
  audioplayers: ^6.5.0
  num_remap: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/route_1/
    - assets/images/route_2/
    - assets/audio/route_1/ru/
    - assets/audio/route_1/tat/
    - assets/audio/route_2/ru/
    - assets/audio/route_2/tat/
    - assets/data/routes.json